### ISSUE TITLE
Cannot use atomicwrites on filename with no directory component

### ISSUE THREAD

**Issue by DarwinAwardWinner** [untitaker/python-atomicwrites#19]
When running the example in the README with atomicwrites 1.1.0:

```
from atomicwrites import atomic_write

with atomic_write('foo.txt', overwrite=True) as f:
    f.write('Hello world.')
```

I get:

```
Traceback (most recent call last):
  File "/Users/ryan/temp/atomictest.py", line 4, in <module>
    f.write('Hello world.')
  File "/Users/ryan/.pyenv/versions/3.5.2/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/Users/ryan/.pyenv/versions/3.5.2/lib/python3.5/site-packages/atomicwrites/__init__.py", line 152, in _open
    self.commit(f)
  File "/Users/ryan/.pyenv/versions/3.5.2/lib/python3.5/site-packages/atomicwrites/__init__.py", line 177, in commit
    replace_atomic(f.name, self._path)
  File "/Users/ryan/.pyenv/versions/3.5.2/lib/python3.5/site-packages/atomicwrites/__init__.py", line 89, in replace_atomic
    return _replace_atomic(src, dst)
  File "/Users/ryan/.pyenv/versions/3.5.2/lib/python3.5/site-packages/atomicwrites/__init__.py", line 46, in _replace_atomic
    _sync_directory(os.path.dirname(dst))
  File "/Users/ryan/.pyenv/versions/3.5.2/lib/python3.5/site-packages/atomicwrites/__init__.py", line 38, in _sync_directory
    fd = os.open(directory, 0)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

The reason is that `os.path.dirname('foo.txt')` returns `''` instead of `'.'`.

It looks like a bug was introduced here: https://github.com/untitaker/python-atomicwrites/commit/4c7de64e07240e91482a845afc122e3c6aff0bb1#diff-530c1a5f2cffcd30669f3bb3ebbafc75R31

**Comment by DarwinAwardWinner** [comment]
FWIW, the tests didn't catch this because they all use `tmpdir.join('ha')` to generate filenames to use, so all the tested file names have slashes in them.
